package com.github.aakumykov.sync_dir_to_cloud.aa_v5.common

enum class SyncOperation6 {
    COPY_FROM_SOURCE_TO_TARGET,
    COPY_FROM_TARGET_TO_SOURCE,

    COPY_FROM_SOURCE_TO_TARGET_WITH_BACKUP,
    COPY_FROM_TARGET_TO_SOURCE_WITH_BACKUP,

    MUTUAL_RENAME_AND_COPY,

    DELETE_IN_SOURCE,
    DELETE_IN_TARGET,

    DELETE_IN_TARGET_WITH_BACKUP,
    DELETE_IN_SOURCE_WITH_BACKUP,
}